/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Kanonbot: typeof import('./src/components/kanonbot.vue')['default']
    Main: typeof import('./src/components/main.vue')['default']
    Meowpad: typeof import('./src/components/meowpad.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Support: typeof import('./src/components/support.vue')['default']
    Teamspeak: typeof import('./src/components/teamspeak.vue')['default']
  }
}
