/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/home/about.vue')['default']
    AnchorPoint: typeof import('./src/components/home/anchor-point.vue')['default']
    copy: typeof import('./src/components/register/step-2 copy.vue')['default']
    Discord: typeof import('./src/components/home/discord.vue')['default']
    Footer: typeof import('./src/components/home/footer.vue')['default']
    Kanonbot: typeof import('./src/components/home/kanonbot.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Main: typeof import('./src/components/home/main.vue')['default']
    Meowpad: typeof import('./src/components/home/meowpad.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NResult: typeof import('naive-ui')['NResult']
    NRow: typeof import('naive-ui')['NRow']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Step-': typeof import('./src/components/register/step-.vue')['default']
    Step1: typeof import('./src/components/register/step-1.vue')['default']
    Step2: typeof import('./src/components/register/step-2.vue')['default']
    Step3: typeof import('./src/components/register/step-3.vue')['default']
    Support: typeof import('./src/components/home/support.vue')['default']
  }
}
