/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/home/about.vue')['default']
    AnchorPoint: typeof import('./src/components/home/anchor-point.vue')['default']
    DefaultModal: typeof import('./src/components/home/device/default-modal.vue')['default']
    Device: typeof import('./src/components/home/device.vue')['default']
    Discord: typeof import('./src/components/home/discord.vue')['default']
    Footer: typeof import('./src/components/home/footer.vue')['default']
    Kanonbot: typeof import('./src/components/home/kanonbot.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Main: typeof import('./src/components/home/main.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEl: typeof import('naive-ui')['NEl']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NPropselect: typeof import('naive-ui')['NPropselect']
    NProvider: typeof import('naive-ui')['NProvider']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Randombg: typeof import('./src/components/home/main/randombg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Support: typeof import('./src/components/home/support.vue')['default']
    V2: typeof import('./src/components/home/device/v2.vue')['default']
    V2Se: typeof import('./src/components/home/device/v2-se.vue')['default']
  }
}
